version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/packages/db"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/packages/ingest"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/packages/lib"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/packages/scripts"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/packages/terminal"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/packages/web"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
