previewsEnabled: false

services:
  - type: redis
    name: redis-starter-ingest-2
    region: ohio
    plan: starter
    maxmemoryPolicy: noeviction # recommended for message queues
    ipAllowList: []

  - type: worker
    name: ingest-v-2
    region: ohio
    runtime: node
    plan: standard
    buildCommand: bun install
    startCommand: (cd packages/ingest && bun run production)
    envVars:
      - fromGroup: kong
      - key: NODE_VERSION
        value: lts
      - key: REDIS_HOST
        fromService:
          type: redis
          name: redis-starter-ingest-2
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: redis-starter-ingest-2
          property: port
