subscriptions:
  - id: 'S_YVUSD_APR'
    url: 'https://yearn-yvusd-apr-service.vercel.app/api/webhook'
    abiPath: 'yearn/3/vault'
    type: 'timeseries'
    labels: ['yvusd-estimated-apr', 'locked-yvusd-estimated-apr']
    filter:
      contracts:
        - chainId: 1
          address: '0x696d02Db93291651ED510704c9b286841d506987'
        - chainId: 1
          address: '0xAaaFEa48472f77563961Cdb53291DEDfB46F9040'

  - id: 'S_KATANA_APR'
    url: 'https://katana-apr.yearn.fi/api/webhook'
    abiPath: 'yearn/3/vault'
    type: 'timeseries'
    labels: ['katana-estimated-apr']
    filter:
      chainIds: [747474]
