name: lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun --filter ingest lint
      - run: bun --filter lib lint
      - run: bun --filter terminal lint
      - run: bun --filter web lint
